apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sv2yxfta8-nodejs 
  janus-idp.io/tekton: sv2yxfta8-nodejs
  backstage.io/kubernetes-id: sv2yxfta8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sv2yxfta8-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml